# -*- coding: utf-8 -*-
"""Task-02 Image Generation (Clean Version).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qm4BJWjBTvLdyO_aQQN9a00zEktctqUm
"""

# ============================================
# TASK-02: Image Generation with Stable Diffusion
# ============================================

# Install libraries
!pip install diffusers transformers accelerate torch pillow -q

import torch
from diffusers import StableDiffusionPipeline
from PIL import Image
import matplotlib.pyplot as plt
import os

print("TASK-02: Image Generation")
print("=" * 50)

# Load model
print("Loading model...")
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    safety_checker=None,
    requires_safety_checker=False
)

pipe = pipe.to("cuda")
pipe.enable_attention_slicing()
print("Model loaded!")

# Prompts
prompts = [
    "A futuristic city with flying cars at sunset",
    "An astronaut riding a horse on Mars",
    "A cat wearing a wizard hat, fantasy art",
    "Cyberpunk street market at night",
    "Peaceful lake in a fantasy forest"
]

print(f"Using {len(prompts)} prompts")

# Create output directory
os.makedirs("images", exist_ok=True)

# Generate images
print("\nGenerating images...")

fig, axes = plt.subplots(2, 3, figsize=(12, 8))
axes = axes.ravel()

for i, prompt in enumerate(prompts):
    print(f"Generating image {i+1}: {prompt[:30]}...")

    image = pipe(
        prompt,
        height=512,
        width=512,
        num_inference_steps=30,
        guidance_scale=7.5
    ).images[0]

    filename = f"images/image_{i+1}.png"
    image.save(filename)

    axes[i].imshow(image)
    axes[i].set_title(f"Image {i+1}", fontsize=9)
    axes[i].axis('off')

    print(f"Saved: {filename}")

# Hide unused subplot
axes[5].axis('off')

plt.tight_layout()
plt.savefig("all_images.png", dpi=120)
plt.show()

# Create prompt file
with open("prompts.txt", "w") as f:
    for i, prompt in enumerate(prompts, 1):
        f.write(f"Image {i}: {prompt}\n")

print("\n" + "=" * 50)
print("Generated files:")
print("- images/image_1.png to image_5.png")
print("- all_images.png (grid)")
print("- prompts.txt")
print("=" * 50)

# Download
from google.colab import files
for i in range(1, 6):
    files.download(f"images/image_{i}.png")
files.download("all_images.png")
files.download("prompts.txt")